# ==============================================================================
# ANSIBLE INVENTORY FILE (hosts.ini)
# ==============================================================================

# Local Control Node
[control]
localhost ansible_connection=local

# Managed Remote Virtual Machines (SSH)
[studentvms]
vm1 ansible_host=192.168.56.101
vm2 ansible_host=192.168.56.102

[studentvms:vars]
ansible_user=danish

[managed_nodes:children]
studentvms


# Parent Group
[all_servers:children]
control
managed_nodes

# Global Settings
[all:vars]
ansible_python_interpreter=/usr/bin/python3
